services:
  redis:
    image: alexsuf/redis
    container_name: dash_redis
    volumes:
      - redis_db:/data

  server:
    image: alexsuf/redash
    container_name: dash_server
    depends_on:
      - redis
      - dash_db
    environment:
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://postgres:secret@dash_db:5432/dash
      REDASH_COOKIE_SECRET: aleksey_zadonsky_secret_key
      REDASH_SECRET_KEY: aleksey_zadonsky_secret_key
      PYTHONUNBUFFERED: 0
      TZ: Europe/Moscow
    ports:
      - "5002:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: server

  worker:
    image: alexsuf/redash
    container_name: dash_worker
    depends_on:
      - redis
      - dash_db
    environment:
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://postgres:secret@dash_db:5432/dash
      REDASH_COOKIE_SECRET: aleksey_zadonsky_secret_key
      REDASH_SECRET_KEY: aleksey_zadonsky_secret_key
      QUEUES: queries,scheduled_queries,celery
      WORKERS_COUNT: 2
      TZ: Europe/Moscow
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: worker

  scheduler:
    image: alexsuf/redash
    container_name: dash_scheduler
    depends_on:
      - redis
      - dash_db
    environment:
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://postgres:secret@dash_db:5432/dash
      REDASH_COOKIE_SECRET: aleksey_zadonsky_secret_key
      REDASH_SECRET_KEY: aleksey_zadonsky_secret_key
      QUEUES: scheduled_queries
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: scheduler

  dash_db:
    image: alexsuf/postgres
    container_name: dash_db
    restart: always
    ports:
      - 1119:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dash
      TZ: Europe/Moscow
    volumes:
      - dash_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  dash_flask:
    image: alexsuf/plot
    container_name: dash_flask
    stdin_open: true
    tty: true
    environment:
      TZ: Europe/Moscow
      CONFIG_DB_USER: postgres
      CONFIG_DB_PASSWORD: secret
      CONFIG_DB_HOST: dash_db
      CONFIG_DB_PORT: 5432
      CONFIG_DB: dash-config
      OPENAI_API_KEY: "your_openai_api_key"
    ports:
      - 5001:5001
    volumes:
      - ./app:/app
    command: "python3 /app/app.py"

volumes:
  dash_postgres:
    external: true
  redis_db:
    external: true
